[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "./lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = "1.1.4"

sea-orm-macros = "1.1.4"
[dependenci1.1.4-orm]
version = "0.12.4" # sea-orm version