//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::categories::Entity as Categories;
pub use super::po_product::Entity as PoProduct;
pub use super::products::Entity as Products;
pub use super::purchase_order::Entity as PurchaseOrder;
pub use super::supplier_product::Entity as SupplierProduct;
pub use super::suppliers::Entity as Suppliers;
pub use super::test_table::Entity as TestTable;
